name: ci

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push amd64
        id: docker_build_amd64
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: booyaabes/kali-linux-full:amd64
      - name: Build and push arm v7
        id: docker_build_arm_v7
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7
          push: true
          tags: booyaabes/kali-linux-full:armv7
      - name: Build and push arm64
        id: docker_build_arm64
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          push: true
          tags: booyaabes/kali-linux-full:arm64
      - name: Create multiarch manifest
        id: docker_create_manifest
        run: docker manifest create booyaabes/kali-linux-full:latest --amend booyaabes/kali-linux-full:arm64 --amend booyaabes/kali-linux-full:armv7 --amend booyaabes/kali-linux-full:amd64
      - name: Push multiarch manifest
        id: docker_push_manifest
        run: docker manifest push booyaabes/kali-linux-full:latest
